"""v1_5_staleness_retention_content_hash

Revision ID: 06ad7ef11fc8
Revises: a5201b46fb1a
Create Date: 2026-10-02 16:13:58.024411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ad7ef11fc8'
down_revision: Union[str, None] = 'a5201b46fb1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── claims: expires_at (nullable — only set on new rows going forward) ─────
    op.add_column('claims', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ── claims: is_stale — default FALSE so existing rows are not stale ────────
    op.add_column('claims', sa.Column(
        'is_stale', sa.Boolean(), nullable=False, server_default=sa.false()
    ))
    # ── sources: content_hash (nullable — populated on next re-fetch) ──────────
    op.add_column('sources', sa.Column('content_hash', sa.String(length=64), nullable=True))
    # ── sources: is_stale — default FALSE so existing rows are not stale ───────
    op.add_column('sources', sa.Column(
        'is_stale', sa.Boolean(), nullable=False, server_default=sa.false()
    ))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'is_stale')
    op.drop_column('sources', 'content_hash')
    op.drop_column('claims', 'is_stale')
    op.drop_column('claims', 'expires_at')
    # ### end Alembic commands ###
